```{r}
library(ggplot2)
```


```{r}
path="D:/MAAL 2/sem 5/DataAnalytics/Project/Anatomy-of-a-Popular-Song-master/data/"
us = read.csv(paste0(path, "/us_waf.csv"))
```




```{r}
us_sun$Date=paste0(us_sun$Year,'-',us_sun$Month,'-',us_sun$Day)
```

```{r}
us_sun$Date=as.Date(us_sun$Date)

```

```{r}
print(typeof(us_sun$Date))
```
??
```{r}
us$Date=paste0(us$Year,'-',us$Month,'-',us$Day)

```

```{r}
us$Date=as.Date(us$Date)
```

```{r}
us_song=us[us$Track.Name %in% c("Sunflower - Spider-Man: Into the Spider-Verse", "Wow.") ,]
``` 


```{r}

min <- as.Date("2019-1-1")
max <- as.Date("2019-6-30")
ggplot(us_song, aes(x = us_song$Date, y = us_song$Position)) + 
  geom_line(aes(color = us_song$Track.Name), size = 1) +
  
  theme_minimal()+scale_x_date(date_labels = "%b/%Y",limits = c(min, max))
```
As you can see for any perticular song as the time increases its rank increases in the table.
Hence we have  to consider not only the features of a song but also the time after release of the song




??


